name: Zip Files

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  zip-files:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        name: [Webclean-All, Webclean-Dark, Webclean-Lite, Webclean-Halloween]
        include:
          - name: Webclean-All
            files: Webclean-Dark/ Webclean-Lite/ Webclean-Halloween/
          - name: Webclean-Dark
            files: Webclean-Dark/
          - name: Webclean-Lite
            files: Webclean-Lite/
          - name: Webclean-Halloween
            files: Webclean-Halloween/

    steps:
      - uses: actions/checkout@v3
      - name: Zip ${{ matrix.name }}
        uses: vimtor/action-zip@v1
        with:
          files: ${{ matrix.files }}
          recursive: false
          dest: {{ matrix.name }}.zip
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Webclean-Artifacts
          path: |
            ${{ github.workspace }}/{{ matrix.name }}.zip
      - name: Upload Zips To Release
        uses: svenstaro/upload-release-action@2.3.0
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ github.workspace }}/{{ matrix.name }}.zip
          asset_name: {{ matrix.name }}.zip
          tag: ${{ github.ref }}
          overwrite: true