name: Zip Files

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  zip-files:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        name: [Webclean-All, Webclean-Dark, Webclean-Lite, Webclean-Halloween]
        include:
          - name: Webclean-All
            asset_suffix: All
          - name: Webclean-Dark
            asset_suffix: Dark
          - name: Webclean-Lite
            asset_suffix: Lite
          - name: Webclean-Halloween
            asset_suffix: Halloween
            
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Zip Webclean X3CL Skins
        uses: vimtor/action-zip@v1
        with:
          files: Webclean-Dark/ Webclean-Lite/ Webclean-Halloween/
          recursive: false
          dest: Webclean-All-X3CL-Skin.zip
      - name: Zip Webclean Dark
        uses: vimtor/action-zip@v1
        with:
          files: Webclean-Dark/
          recursive: false
          dest: Webclean-Dark-X3CL-Skin.zip
      - name: Zip Webclean Lite
        uses: vimtor/action-zip@v1
        with:
          files: Webclean-Lite/
          recursive: false
          dest: Webclean-Lite-X3CL-Skin.zip
      - name: Zip Webclean Halloween
        uses: vimtor/action-zip@v1
        with:
          files: Webclean-Halloween/
          recursive: false
          dest: Webclean-Halloween-X3CL-Skin.zip
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Webclean-Artifacts
          path: |
            ${{ github.workspace }}/Webclean-${{ matrix.asset_suffix }}.zip
      - name: Upload Zips To Release
        uses: svenstaro/upload-release-action@2.3.0
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ github.workspace }}/Webclean-${{ matrix.asset_suffix }}.zip
          asset_name: Webclean-${{ matrix.asset_suffix }}.zip
          tag: ${{ github.ref }}
          overwrite: true