name: Zip Files

on:
  workflow_dispatch:
  release:
    types: [published]
    tags:
      - '*'

jobs:
  zip-files:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - name: Zip Webclean X3CL Skins
        uses: vimtor/action-zip@v1
        with:
          files: Webclean-Dark/ Webclean-Lite/ Webclean-Halloween/
          recursive: true
          dest: Webclean-X3CL-Skins.zip
      - name: Zip Webclean Dark
        uses: vimtor/action-zip@v1
        with:
          files: Webclean-Dark/
          recursive: false
          dest: Webclean-Dark-X3CL-Skin.zip
      - name: Zip Webclean Lite
        uses: vimtor/action-zip@v1
        with:
          files: Webclean-Lite/
          recursive: false
          dest: Webclean-Lite-X3CL-Skin.zip
      - name: Zip Webclean Halloween
        uses: vimtor/action-zip@v1
        with:
          files: Webclean-Halloween/
          recursive: false
          dest: Webclean-Halloween-X3CL-Skin.zip
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: my-artifacts
          path: |
            ${{ github.workspace }}/Webclean-X3CL-Skins.zip
            ${{ github.workspace }}/Webclean-Dark-X3CL-Skin.zip
            ${{ github.workspace }}/Webclean-Lite-X3CL-Skin.zip
            ${{ github.workspace }}/Webclean-Halloween-X3CL-Skin.zip
      - name: Upload Releases
        uses: ncipollo/release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          artifacts: "Webclean-X3CL-Skins.zip, Webclean-Dark-X3CL-Skin.zip, Webclean-Lite-X3CL-Skin.zip, Webclean-Halloween-X3CL-Skin.zip"
          token: ${{ secrets.GITHUB_TOKEN }}