name: Zip Files

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  zip-files:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        name: [Webclean-All, Webclean-Dark, Webclean-Lite, Webclean-Halloween]
        include:
          - name: Webclean-All
            folder: Webclean-Dark Webclean-Lite Webclean-Halloween
          - name: Webclean-Dark
            folder: Webclean-Dark
          - name: Webclean-Lite
            folder: Webclean-Lite
          - name: Webclean-Halloween
            folder: Webclean-Halloween

    steps:
      - uses: actions/checkout@v3
      - name: Zip ${{ matrix.name }}
        uses: montudor/action-zip@v1.0.0
        with:
          args: zip -qq -r ${{ matrix.name }}.zip ${{ matrix.folder }}
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Webclean-Artifacts
          path: |
            ${{ github.workspace }}/${{ matrix.name }}.zip
      - name: Upload Zips To Release
        uses: svenstaro/upload-release-action@2.3.0
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ github.workspace }}/${{ matrix.name }}.zip
          asset_name: ${{ matrix.name }}.zip
          tag: ${{ github.ref }}
          overwrite: true